version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        container_name: slim
        build: ./docker
        ports:
          - 8000:80
        tty: true
        stdin_open: true
        volumes:
            - ./:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/php.ini
            - ./logs:/var/log/apache2

    composer:
        image: composer
        volumes:
          - .:/app
        working_dir: /app
        command: composer install