name: deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: export ssh keys
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          echo ${{ secrets.KNOWN_HOSTS }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name: backup words file
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_DIR }} && mv resources/words.txt ."

      - name: delete server files
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_DIR }} && rm -rf app public resources src vendor composer.*"

      - name: upload files
        run: scp -p -P ${{ secrets.SSH_PORT }} -r app public resources src composer.* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DIR }}/.

      - name: install composer
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_DIR }} && php8.1 ~/bin/composer install"

      - name: revert words file
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_DIR }} && mv words.txt resources/."

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,action,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}