name: Tests

on: [push, pull_request]

jobs:
    tests:
        name: Tests PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2]
                experimental: [false]
                include:
                    - php: 8.1

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug
            
            - name: Set up MeCab
              run: |
                sudo apt-get update
                sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8

            - name: Check MeCab
              run: |
                mecab --version
                which mecab

            - name: cache vendor
              id: cache
              uses: actions/cache@v4
              with:
                path: ./vendor
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: composer install
              if: steps.cache.outputs.cache-hit != 'true'
              run: docker-compose up composer

            - name: Coding standards
              if: matrix.analysis
              run: vendor/bin/phpcs

            - name: Static analysis
              if: matrix.analysis
              run: vendor/bin/phpstan

            - name: Tests
              run: vendor/bin/phpunit --coverage-clover clover.xml