name: Tests

on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - app/**
      - public/**
      - src/**
      - testFile/**
      - tests/**
      - composer.*
      - docker-compose.yml
      - docker/composer/**
      - phpcs.xml
      - phpstan.neon.dist
      - phpunit.xml

env:
  PHP_VERSION: "8.5"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up PHP ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - name: Set up MeCab
        run: |
          sudo apt-get update
          sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8

      - name: Check MeCab
        run: |
          mecab --version
          which mecab

      - name: Cache vendor
        id: cache
        uses: actions/cache@v6
        with:
          path: ./vendor
          key: ${{ runner.os }}-php${{ env.PHP_VERSION }}-composer-${{ hashFiles('composer.json', 'composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ env.PHP_VERSION }}-composer-

      - name: Composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker compose up composer

      - name: Coding standards
        run: vendor/bin/phpcs

      - name: Static analysis
        run: vendor/bin/phpstan

      - name: Tests
        run: vendor/bin/phpunit
